CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "vector";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

CREATE DATABASE langfuse;
GRANT ALL PRIVILEGES ON DATABASE langfuse TO legalops;
